platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!
source 'https://cdn.cocoapods.org/'

target 'PHRSATHealthBridge' do
  pod 'Alamofire', '5.8.0'
  pod 'KeychainAccess', '4.2.2'
  pod 'CryptoSwift', '1.8.0'
  pod 'SwiftyJSON', '5.0.1'
  pod 'Charts', '4.1.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'PHRSATHealthBridgeTests' do
    inherit! :search_paths
    pod 'Quick', '7.0.0'
    pod 'Nimble', '12.0.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['ENABLE_APP_SANDBOX'] = 'YES'
      config.build_settings['ENABLE_HARDENED_RUNTIME'] = 'YES'
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'YES'
      config.build_settings['GCC_WARN_UNDECLARED_SELECTOR'] = 'YES'
      config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'YES'
      config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
      config.build_settings['VALIDATE_PRODUCT'] = 'YES'
      config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'YES'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
      config.build_settings['ENABLE_TESTABILITY'] = config.name == 'Debug' ? 'YES' : 'NO'
      config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = config.name == 'Debug' ? 'DEBUG' : ''
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end