apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base namespace for all resources
namespace: phrsat

# List of all resources to be included in the base configuration
resources:
  # Core namespace definition
  - namespace.yaml
  
  # API Service resources
  - ../apps/api/deployment.yaml
  - ../apps/api/service.yaml
  - ../apps/api/configmap.yaml
  - ../apps/api/secret.yaml
  
  # Web Application resources
  - ../apps/web/deployment.yaml
  - ../apps/web/service.yaml
  - ../apps/web/configmap.yaml
  
  # Background Workers
  - ../apps/workers/deployment.yaml
  - ../apps/workers/configmap.yaml
  
  # Monitoring Stack
  - ../monitoring/prometheus/deployment.yaml
  - ../monitoring/grafana/deployment.yaml
  - ../monitoring/alertmanager/deployment.yaml
  
  # Security Policies
  - ../security/networkpolicy.yaml
  - ../security/podsecuritypolicy.yaml
  - ../security/rbac.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: phrsat
  app.kubernetes.io/part-of: phrsat-platform
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: infrastructure
  security.phrsat.com/compliance: hipaa
  monitoring.phrsat.com/enabled: "true"

# Common annotations applied to all resources
commonAnnotations:
  maintainer: "PHRSAT Platform Team"
  contact: "platform@phrsat.com"
  description: "Personal Health Record Store and Analysis Tool"
  security.phrsat.com/last-review: "2023-10-01"
  monitoring.phrsat.com/grafana-dashboard: "phrsat-platform"