apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: phrsat
  labels:
    app: alertmanager
    component: monitoring
    part-of: observability-stack
    managed-by: kubernetes
  annotations:
    # Prometheus service discovery
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
    
    # Service mesh configuration
    service.istio.io/canonical-name: "alertmanager"
    service.istio.io/canonical-revision: "v1"
    
    # DataDog monitoring integration
    datadog.com/service: "alertmanager"
    datadog.com/component: "monitoring"

spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9093
      targetPort: 9093
      protocol: TCP
      appProtocol: http
    - name: cluster
      port: 9094
      targetPort: 9094
      protocol: TCP
      appProtocol: tcp
  selector:
    app: alertmanager
    component: monitoring
  sessionAffinity: None
  publishNotReadyAddresses: false