apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: phrsat
  labels:
    app: phrsat-api
    component: api
    environment: ${ENV_STATE}
  annotations:
    description: "API service configuration for PHRSAT platform"
    compliance: "HIPAA-compliant configuration"
    version: "1.0.0"
data:
  # Core Application Settings
  APP_NAME: "phrsat-api"
  API_VERSION: "v1"
  API_TITLE: "PHRSAT API"
  API_DESCRIPTION: "Personal Health Record Store and Analysis Tool API"
  DEBUG: "false"

  # API Documentation Settings
  OPENAPI_URL: "/openapi.json"
  DOCS_URL: "/docs"

  # Security Settings
  ALLOWED_HOSTS: "*.phrsat.com,api.phrsat.com"
  CORS_ORIGINS: "https://app.phrsat.com,https://portal.phrsat.com"
  CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_HEADERS: "Authorization,Content-Type,X-API-Key,X-Request-ID"
  
  # Rate Limiting Configuration
  RATE_LIMIT_PER_MINUTE: "60"
  RATE_LIMIT_BURST: "120"
  RATE_LIMIT_HEALTHCARE_PROVIDER: "120"
  RATE_LIMIT_TIMEFRAME: "1"

  # Security Headers
  SECURITY_HEADERS: |
    {
      "X-Frame-Options": "DENY",
      "X-Content-Type-Options": "nosniff",
      "X-XSS-Protection": "1; mode=block",
      "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
      "Content-Security-Policy": "default-src 'self'",
      "Referrer-Policy": "strict-origin-when-cross-origin"
    }

  # Health Data Configuration
  HEALTH_DATA_FORMAT: "FHIR_R4"
  FHIR_VERSION: "4.0.1"

  # Monitoring Configuration
  MONITORING_ENABLED: "true"
  AUDIT_ENABLED: "true"
  AUDIT_LOG_REQUESTS: "true"
  AUDIT_LOG_RESPONSES: "true"
  AUDIT_RETENTION_DAYS: "90"
  AUDIT_EXCLUDE_PATHS: "/health,/metrics"

  # Feature Flags
  FEATURE_FLAGS: |
    {
      "enable_ai_analysis": true,
      "enable_document_ocr": true,
      "enable_health_predictions": true,
      "enable_real_time_sync": true
    }

  # Environment-Specific Overrides
  production:
    DEBUG: "false"
    DOCS_URL: ""
    OPENAPI_URL: ""
    RATE_LIMIT_PER_MINUTE: "30"
    CORS_ORIGINS: "https://app.phrsat.com"
    MONITORING_ENABLED: "true"
    AUDIT_ENABLED: "true"

  staging:
    DEBUG: "false"
    RATE_LIMIT_PER_MINUTE: "60"
    MONITORING_ENABLED: "true"
    AUDIT_ENABLED: "true"

  development:
    DEBUG: "true"
    RATE_LIMIT_PER_MINUTE: "120"
    CORS_ORIGINS: "http://localhost:3000,http://localhost:8080"
    MONITORING_ENABLED: "true"
    AUDIT_ENABLED: "true"