# PHRSAT API Secrets Configuration
# Version: 1.0.0
# Enhanced security measures and HIPAA compliance for sensitive data storage
apiVersion: v1
kind: Secret
metadata:
  name: phrsat-api-secrets
  namespace: phrsat
  labels:
    app: phrsat-api
    component: secrets
    compliance: hipaa
    security-tier: high
  annotations:
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/last-rotated: "2023-10-01T00:00:00Z"
    secret.kubernetes.io/encryption-algorithm: "AES-256-GCM"
    secret.kubernetes.io/backup-enabled: "true"
    secret.kubernetes.io/audit-level: "strict"
    argocd.argoproj.io/sync-wave: "1"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "phrsat-api"
type: Opaque
stringData:
  # Core Application Secrets
  SECRET_KEY: "${PHRSAT_SECRET_KEY}"
  JWT_SECRET_KEY: "${PHRSAT_JWT_SECRET_KEY}"
  ENCRYPTION_KEY: "${PHRSAT_ENCRYPTION_KEY}"

  # Database Connection Strings
  DATABASE_URL: "${MONGODB_URL}?retryWrites=true&w=majority&ssl=true&authSource=admin"
  REDIS_URL: "${REDIS_URL}?ssl=true&ssl_cert_reqs=required"

  # AWS Credentials
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_KMS_KEY_ID: "${AWS_KMS_KEY_ID}"

  # OAuth Configuration
  OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
  OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"

  # Security Configuration
  MFA_SECRET_KEY: "${MFA_SECRET_KEY}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  BACKUP_ENCRYPTION_KEY: "${BACKUP_ENCRYPTION_KEY}"

immutable: true